In [1]:
import os
# Data Handling
import numpy as np
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Train Test Split
from sklearn.model_selection import train_test_split

# Preprocessing
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

# Pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Saving the preprocessor
import joblib

In [ ]:
train_df = pd.read_csv("train.csv")
test_df  = pd.read_csv("test.csv")
print(train_df.shape)
print(test_df.shape)

(1200000, 21)
(800000, 20)

In [3]:
print(train_df.head())

   id   Age  Gender  Annual Income Marital Status  Number of Dependents  \
0   0  19.0  Female        10049.0        Married                   1.0
1   1  39.0  Female        31678.0       Divorced                   3.0
2   2  23.0    Male        25602.0       Divorced                   3.0
3   3  21.0    Male       141855.0        Married                   2.0
4   4  21.0    Male        39651.0         Single                   1.0

  Education Level     Occupation  Health Score  Location  ... Previous Claims  \
0      Bachelor's  Self-Employed     22.598761     Urban  ...             2.0
1        Master's            NaN     15.569731     Rural  ...             1.0
2     High School  Self-Employed     47.177549  Suburban  ...             1.0
3      Bachelor's            NaN     10.938144     Rural  ...             1.0
4      Bachelor's  Self-Employed     20.376094     Rural  ...             0.0

   Vehicle Age  Credit Score  Insurance Duration           Policy Start Date  \
0         17.0         372.0                 5.0  2023-12-23 15:21:39.134960
1         12.0         694.0                 2.0  2023-06-12 15:21:39.111551
2         14.0           NaN                 3.0  2023-09-30 15:21:39.221386
3          0.0         367.0                 1.0  2024-06-12 15:21:39.226954
4          8.0         598.0                 4.0  2021-12-01 15:21:39.252145

  Customer Feedback Smoking Status Exercise Frequency Property Type  \
0              Poor             No             Weekly         House
1           Average            Yes            Monthly         House
2              Good            Yes             Weekly         House
3              Poor            Yes              Daily     Apartment
4              Poor            Yes             Weekly         House

  Premium Amount
0         2869.0
1         1483.0
2          567.0
3          765.0
4         2022.0

[5 rows x 21 columns]

In [4]:
print(test_df.head())

        id   Age  Gender  Annual Income Marital Status  Number of Dependents  \
0  1200000  28.0  Female         2310.0            NaN                   4.0
1  1200001  31.0  Female       126031.0        Married                   2.0
2  1200002  47.0  Female        17092.0       Divorced                   0.0
3  1200003  28.0  Female        30424.0       Divorced                   3.0
4  1200004  24.0    Male        10863.0       Divorced                   2.0

  Education Level     Occupation  Health Score  Location    Policy Type  \
0      Bachelor's  Self-Employed      7.657981     Rural          Basic
1        Master's  Self-Employed     13.381379  Suburban        Premium
2             PhD     Unemployed     24.354527     Urban  Comprehensive
3             PhD  Self-Employed      5.136225  Suburban  Comprehensive
4     High School     Unemployed     11.844155  Suburban        Premium

   Previous Claims  Vehicle Age  Credit Score  Insurance Duration  \
0              NaN         19.0           NaN                 1.0
1              NaN         14.0         372.0                 8.0
2              NaN         16.0         819.0                 9.0
3              1.0          3.0         770.0                 5.0
4              NaN         14.0         755.0                 7.0

            Policy Start Date Customer Feedback Smoking Status  \
0  2023-06-04 15:21:39.245086              Poor            Yes
1  2024-04-22 15:21:39.224915              Good            Yes
2  2023-04-05 15:21:39.134960           Average            Yes
3  2023-10-25 15:21:39.134960              Poor            Yes
4  2021-11-26 15:21:39.259788           Average             No

  Exercise Frequency Property Type
0             Weekly         House
1             Rarely     Apartment
2            Monthly         Condo
3              Daily         House
4             Weekly         House

In [5]:
# Check for missing values
print(train_df.isnull().sum())

id                           0
Age                      18705
Gender                       0
Annual Income            44949
Marital Status           18529
Number of Dependents    109672
Education Level              0
Occupation              358075
Health Score             74076
Location                     0
Policy Type                  0
Previous Claims         364029
Vehicle Age                  6
Credit Score            137882
Insurance Duration           1
Policy Start Date            0
Customer Feedback        77824
Smoking Status               0
Exercise Frequency           0
Property Type                0
Premium Amount               0
dtype: int64

In [6]:
print(test_df.isnull().sum())

id                           0
Age                      12489
Gender                       0
Annual Income            29860
Marital Status           12336
Number of Dependents     73130
Education Level              0
Occupation              239125
Health Score             49449
Location                     0
Policy Type                  0
Previous Claims         242802
Vehicle Age                  3
Credit Score             91451
Insurance Duration           2
Policy Start Date            0
Customer Feedback        52276
Smoking Status               0
Exercise Frequency           0
Property Type                0
dtype: int64

In [7]:
train_df.columns

Index(['id', 'Age', 'Gender', 'Annual Income', 'Marital Status',
       'Number of Dependents', 'Education Level', 'Occupation', 'Health Score',
       'Location', 'Policy Type', 'Previous Claims', 'Vehicle Age',
       'Credit Score', 'Insurance Duration', 'Policy Start Date',
       'Customer Feedback', 'Smoking Status', 'Exercise Frequency',
       'Property Type', 'Premium Amount'],
      dtype='object')

In [8]:
test_df.columns

Index(['id', 'Age', 'Gender', 'Annual Income', 'Marital Status',
       'Number of Dependents', 'Education Level', 'Occupation', 'Health Score',
       'Location', 'Policy Type', 'Previous Claims', 'Vehicle Age',
       'Credit Score', 'Insurance Duration', 'Policy Start Date',
       'Customer Feedback', 'Smoking Status', 'Exercise Frequency',
       'Property Type'],
      dtype='object')

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1200000 non-null  int64
 1   Age                   1181295 non-null  float64
 2   Gender                1200000 non-null  object
 3   Annual Income         1155051 non-null  float64
 4   Marital Status        1181471 non-null  object
 5   Number of Dependents  1090328 non-null  float64
 6   Education Level       1200000 non-null  object
 7   Occupation            841925 non-null   object
 8   Health Score          1125924 non-null  float64
 9   Location              1200000 non-null  object
 10  Policy Type           1200000 non-null  object
 11  Previous Claims       835971 non-null   float64
 12  Vehicle Age           1199994 non-null  float64
 13  Credit Score          1062118 non-null  float64
 14  Insurance Duration    1199999 non-null  float64
 15  Policy Start Date     1200000 non-null  object
 16  Customer Feedback     1122176 non-null  object
 17  Smoking Status        1200000 non-null  object
 18  Exercise Frequency    1200000 non-null  object
 19  Property Type         1200000 non-null  object
 20  Premium Amount        1200000 non-null  float64
dtypes: float64(9), int64(1), object(11)
memory usage: 192.3+ MB

In [10]:
train_df.describe()

,id,Age,Annual Income,Number of Dependents,Health Score,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Premium Amount
count,1.200000e+06,1.181295e+06,1.155051e+06,1.090328e+06,1.125924e+06,835971.000000,1.199994e+06,1.062118e+06,1.199999e+06,1.200000e+06
mean,5.999995e+05,4.114556e+01,3.274522e+04,2.009934e+00,2.561391e+01,1.002689,9.569889e+00,5.929244e+02,5.018219e+00,1.102545e+03
std,3.464103e+05,1.353995e+01,3.217951e+04,1.417338e+00,1.220346e+01,0.982840,5.776189e+00,1.499819e+02,2.594331e+00,8.649989e+02
min,0.000000e+00,1.800000e+01,1.000000e+00,0.000000e+00,2.012237e+00,0.000000,0.000000e+00,3.000000e+02,1.000000e+00,2.000000e+01
25%,2.999998e+05,3.000000e+01,8.001000e+03,1.000000e+00,1.591896e+01,0.000000,5.000000e+00,4.680000e+02,3.000000e+00,5.140000e+02
50%,5.999995e+05,4.100000e+01,2.391100e+04,2.000000e+00,2.457865e+01,1.000000,1.000000e+01,5.950000e+02,5.000000e+00,8.720000e+02
75%,8.999992e+05,5.300000e+01,4.463400e+04,3.000000e+00,3.452721e+01,2.000000,1.500000e+01,7.210000e+02,7.000000e+00,1.509000e+03
max,1.199999e+06,6.400000e+01,1.499970e+05,4.000000e+00,5.897591e+01,9.000000,1.900000e+01,8.490000e+02,9.000000e+00,4.999000e+03

In [11]:
train_df.duplicated().sum()

np.int64(0)

In [12]:
# Drop unwanted columns
train_df.drop(["id", "Customer Feedback"], axis=1, inplace=True)

# Convert to datetime
train_df["Policy Start Date"] = pd.to_datetime(train_df["Policy Start Date"], errors="coerce")

# Extract date features
train_df["Policy_Year"] = train_df["Policy Start Date"].dt.year
train_df["Policy_Month"] = train_df["Policy Start Date"].dt.month
train_df["Policy_Day"] = train_df["Policy Start Date"].dt.day

# Remove original date column
train_df.drop("Policy Start Date", axis=1, inplace=True)

# Check result
train_df.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,...,Vehicle Age,Credit Score,Insurance Duration,Smoking Status,Exercise Frequency,Property Type,Premium Amount,Policy_Year,Policy_Month,Policy_Day
0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,Premium,...,17.0,372.0,5.0,No,Weekly,House,2869.0,2023,12,23
1,39.0,Female,31678.0,Divorced,3.0,Master's,NaN,15.569731,Rural,Comprehensive,...,12.0,694.0,2.0,Yes,Monthly,House,1483.0,2023,6,12
2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,Premium,...,14.0,NaN,3.0,Yes,Weekly,House,567.0,2023,9,30
3,21.0,Male,141855.0,Married,2.0,Bachelor's,NaN,10.938144,Rural,Basic,...,0.0,367.0,1.0,Yes,Daily,Apartment,765.0,2024,6,12
4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,Premium,...,8.0,598.0,4.0,Yes,Weekly,House,2022.0,2021,12,1

In [13]:
# Identify numerical and categorical columns
numerical_cols = train_df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = train_df.select_dtypes(include=['object']).columns
print("Numerical Columns:", numerical_cols)
print("Categorical Columns:", categorical_cols)

Numerical Columns: Index(['Age', 'Annual Income', 'Number of Dependents', 'Health Score',
       'Previous Claims', 'Vehicle Age', 'Credit Score', 'Insurance Duration',
       'Premium Amount'],
      dtype='object')
Categorical Columns: Index(['Gender', 'Marital Status', 'Education Level', 'Occupation', 'Location',
       'Policy Type', 'Smoking Status', 'Exercise Frequency', 'Property Type'],
      dtype='object')

In [14]:
# Target Variable
y = train_df["Premium Amount"]

# Features
X = train_df.drop("Premium Amount", axis=1)

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (1200000, 20)
Target Shape : (1200000,)

In [15]:
# Categorical Columns

categorical_cols = X.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

# Numerical Columns

numerical_cols = X.select_dtypes(
    include=["number"]
).columns.tolist()

print("Categorical Columns")
print(categorical_cols)

print("\nNumerical Columns")
print(numerical_cols)

Categorical Columns
['Gender', 'Marital Status', 'Education Level', 'Occupation', 'Location', 'Policy Type', 'Smoking Status', 'Exercise Frequency', 'Property Type']

Numerical Columns
['Age', 'Annual Income', 'Number of Dependents', 'Health Score', 'Previous Claims', 'Vehicle Age', 'Credit Score', 'Insurance Duration', 'Policy_Year', 'Policy_Month', 'Policy_Day']

In [16]:
type(numerical_cols)

list

In [17]:
# Numerical Data Preprocessing

numeric_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

numeric_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [18]:
# Categorical Data Preprocessing

categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)

categorical_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('onehot',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [19]:
# Column Transformer

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numerical_cols
        ),
        (
            "cat",
            categorical_transformer,
            categorical_cols
        )
    ],
    remainder="drop"
)

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['Age', 'Annual Income',
                                  'Number of Dependents', 'Health Score',
                                  'Previous Claims', 'Vehicle Age',
                                  'Credit Score', 'Insurance Duration',
                                  'Policy_Year', 'Policy_Month',
                                  'Policy_Day']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Gender', 'Marital Status', 'Education Level',
                                  'Occupation', 'Location', 'Policy Type',
                                  'Smoking Status', 'Exercise Frequency',
                                  'Property Type'])])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X Train :", X_train.shape)
print("X Test  :", X_test.shape)

print("y Train :", y_train.shape)
print("y Test  :", y_test.shape)

X Train : (960000, 20)
X Test  : (240000, 20)
y Train : (960000,)
y Test  : (240000,)

In [21]:
# Apply preprocessing

X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed  = preprocessor.transform(X_test)

print("Transformed X_train shape:", X_train_transformed.shape)
print("Transformed X_test shape :", X_test_transformed.shape)

Transformed X_train shape: (960000, 38)
Transformed X_test shape : (240000, 38)

In [22]:
# Check for NaN in transformed training data
print("NaN count in X_train_transformed:",
      np.isnan(X_train_transformed).sum())

NaN count in X_train_transformed: 0

In [23]:
print("Original Features :", X.shape[1])

print(
    "Processed Features :",
    X_train_transformed.shape[1]
)

Original Features : 20
Processed Features : 38

In [ ]:
# Save to models/ directory
os.makedirs("models", exist_ok=True)

joblib.dump(
    preprocessor,
    os.path.join("models", "preprocessor.pkl")
)

print("Preprocessor saved to models/preprocessor.pkl")

Preprocessor saved to models/preprocessor.pkl